#!/usr/bin/perl
# $Id: get_streams 42 2008-01-26 21:05:44Z dave $

=head1 NAME

get_streams

=head1 DESCRIPTION

New! Improved! Version of get_streams, the program which extracts information
about radio streams from the BBC web site and writes a YAML file containing
the details.

This second version of the program takes advantage of the XML versions of the
data which the BBC have recently made available.

=cut

use strict;
use warnings;

require BBCRobot;

use XML::LibXML;
use DateTime;
use DateTime::Format::Strptime;
use DateTime::Duration;
use YAML qw(DumpFile);

my $yaml_file = shift || 'streams.yaml';

my $start_url = 'http://www.bbc.co.uk/radio/aod/availability';
my @stations  = qw(radio1 radio2 radio3 radio4 fivelive 1xtra 6music bbc7
                   asiannetwork alba radioscotland radioulster radiofoyle
                   radiowales radiocymru);

my $now = DateTime->now;
my $ua  = BBCRobot->new;
my $p   = XML::LibXML->new;
my $dt  = DateTime::Format::Strptime->new(
  pattern => '%Y-%m-%dT%H:%M:%S%Z',
);

my %stations;

my %xpath = (
  pid      => 'pid',
  title    => 'title',
  service  => 'service',
  synopsis => 'synopsis',
  start    => 'broadcast/@start',
  duration => 'broadcast/@duration',
  av_start => 'availability/@start',
  av_end   => 'availability/@end',
  media    => 'links/link[@type="mediaselector"]',
);

foreach (@stations) {
  process_station("$start_url/$_.xml");
  last;
}

DumpFile $yaml_file, \%stations;

sub process_station {
  warn "Getting $_[0]\n";
  my $resp = $ua->get($_[0]);

  die "$_[0] : ", $resp->status_line unless $resp->is_success;

  my $xml = $p->parse_string($resp->content);

  foreach ($xml->findnodes('//entry')) {
    my $show;

    for my $x (keys %xpath) {
      $show->{$x} = $_->findvalue($xpath{$x});
    }

    $show->{av_start} = $dt->parse_datetime($show->{av_start});
    $show->{av_end}   = $dt->parse_datetime($show->{av_end});

    next unless $show->{av_start} <= $now
         and    $show->{av_end}   >= $now;

    $show->{title} =~ s|,\s*\d\d/\d\d\/\d\d\d\d\s*||;
    $show->{duration} = DateTime::Duration->new(seconds => $show->{duration});
    $show->{start} = $dt->parse_datetime($show->{start});

    $resp = $ua->get($show->{media});
    die "$show->{media} : ", $resp->status_line unless $resp->is_success;

    my $med_xml = $p->parse_string($resp->content);

    $show->{ram} = 

    push @{$stations{$show->{service}}{$show->{title}}}, $show;
  }
}

=head1 AUTHOR

Dave Cross E<lt>dave@dave.org.ukE<gt>

=head1 COPYRIGHT

Copyright 2005-8, Dave Cross, All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
